
def makeChampList():
    champlist=[]
    champlist.append("Aatrox")
    champlist.append("Ahri")
    champlist.append("Akali")
    champlist.append("Alistar")
    champlist.append("Ammumu")
    champlist.append("Anivia")
    champlist.append("Annie")
    champlist.append("Ashe")
    champlist.append("Aurelion Sol")
    champlist.append("Azir")
    champlist.append("Bard")
    champlist.append("Bard")
    champlist.append("Blitzcrank")
    champlist.append("Brand")
    champlist.append("Braum")
    champlist.append("Caitlyn")
    champlist.append("Camile")
    champlist.append("Cassiopeia")
    champlist.append("Cho'Gath")
    champlist.append("Corki")
    champlist.append("Darius")
    champlist.append("Diana")
    champlist.append("Dr.Mundo")
    champlist.append("Draven")
    champlist.append("Ekko")
    champlist.append("Elise")
    champlist.append("Evelynn")
    champlist.append("Ezreal")
    champlist.append("Fiddlesticks")
    champlist.append("Fiora")
    champlist.append("Fizz")
    champlist.append("Galio")
    champlist.append("Gangplank")
    champlist.append("Garen")
    champlist.append("Gnar")
    champlist.append("Gragas")
    champlist.append("Graves")
    champlist.append("Hecarim")
    champlist.append("Heimerdinger")
    champlist.append("Illaoi")
    champlist.append("Irelia")
    champlist.append("Ivern")
    champlist.append("Janna")
    champlist.append("Jarvan IV")
    champlist.append("Jax")
    champlist.append("Jayce")
    champlist.append("Jhin")
    champlist.append("Jinx")
    champlist.append("Kai'Sa")
    champlist.append("Kalista")
    champlist.append("Karma")
    champlist.append("Karthus")
    champlist.append("Kassadin")
    champlist.append("Katarina")
    champlist.append("Kayle")
    champlist.append("Kayn")
    champlist.append("Kennen")
    champlist.append("Kha'Zix")
    champlist.append("Kindred")
    champlist.append("Kled")
    champlist.append("Kog'Maw")
    champlist.append("LeBlanc")
    champlist.append("Lee Sin")
    champlist.append("Leona")
    champlist.append("Lissandra")
    champlist.append("Lucian")
    champlist.append("Lulu")
    champlist.append("Lux")
    champlist.append("Malphite")
    champlist.append("Malzahar")
    champlist.append("Maokai")
    champlist.append("Master Yi")
    champlist.append("Miss Fortune")
    champlist.append("Mordekaiser")
    champlist.append("Morgana")
    champlist.append("Nami")
    champlist.append("Nasus")
    champlist.append("Nautilus")
    champlist.append("Nidalee")
    champlist.append("Nocturne")
    champlist.append("Nunu")
    champlist.append("Olaf")
    champlist.append("Orianna")
    champlist.append("Ornn")
    champlist.append("Pantheon")
    champlist.append("Poppy")
    champlist.append("Quinn")
    champlist.append("Rakan")
    champlist.append("Rammus")
    champlist.append("Rek'Sai")
    champlist.append("Renekton")
    champlist.append("Rengar")
    champlist.append("Riven")
    champlist.append("Rumble")
    champlist.append("Ryze")
    champlist.append("Sejuani")
    champlist.append("Shaco")
    champlist.append("Shen")
    champlist.append("Shyvana")
    champlist.append("Singed")
    champlist.append("Sion")
    champlist.append("Sivir")
    champlist.append("Skarner")
    champlist.append("Sona")
    champlist.append("Soraka")
    champlist.append("Swain")
    champlist.append("Syndra")
    champlist.append("Tahm Kench")
    champlist.append("Taliyah")
    champlist.append("Talon")
    champlist.append("Taric")
    champlist.append("Teemo")
    champlist.append("Thresh")
    champlist.append("Tristana")
    champlist.append("Trundle")
    champlist.append("Tryndamere")
    champlist.append("Twisted Fate")
    champlist.append("Twitch")
    champlist.append("Udyr")
    champlist.append("Urgot")
    champlist.append("Varus")
    champlist.append("Vayne")
    champlist.append("Veigar")
    champlist.append("Vel'Koz")
    champlist.append("Vi")
    champlist.append("Viktor")
    champlist.append("Vladmir")
    champlist.append("Volibear")
    champlist.append("Warwick")
    champlist.append("Wukong")
    champlist.append("Xayah")
    champlist.append("Xerath")
    champlist.append("Xin Zhao")
    champlist.append("Yasuo")
    champlist.append("Yorick")
    champlist.append("Zac")
    champlist.append("Zed")
    champlist.append("Ziggs")
    champlist.append("Zilean")
    champlist.append("Zoe")
    champlist.append("Zyra")
    return champlist

def makeLocation():
    location=[]
    location.append("Anarchy Acres")
    location.append("Haunted Hills")
    location.append("Junk Junction")
    location.append("Pleasent Park")
    location.append("Tilted Towers")
    location.append("Snobby Shores")
    location.append("Greasy Grove")
    location.append("Shifty Shafts")
    location.append("Salty Springs")
    location.append("Loot Lake")
    location.append("Tomato Town")
    location.append("Dusty Divot")
    location.append("Wailing Woods")
    location.append("Lonely Lodge")
    location.append("Retail Row")
    location.append("Moisty Mire")
    location.append("Lucky Landing")
    location.append("Fatal Fields")
    location.append("Flush Factory")
    location.append("Risky Reels")
    return location
